apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - name: mysqldb
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: yourSAFEpassword
        - name: MYSQL_DATABASE
          value: student
        - name: MYSQL_USER
          value: me
        - name: MYSQL_PASSWORD
          value: yourSAFEpassword
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
