apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  strategy: 
    type: Recreate 
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: flask-webserver:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          
