apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      nodeSelector:
        kubernetes.io/hostname: kc-m1
      containers:
      - name: webserver
        image: shaangoswami/flask-webserver:TAG_WILL_BE_SET_BY_JENKINS
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
